version: '3.8'
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 4200:80

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 5000:5000
